### ISSUE TITLE
Gallery Carousels [Back-end]

### ISSUE THREAD

**Issue by nchlnnmrvnz** [yanaagi/cs-expo-2023#95]
- resolve GlideJS warning

**Comment by kylekce** [comment]
Can I have more details on the warning?

**Comment by kylekce** [comment]
Ah, if you're referring to this warning:
![Screenshot (407)](https://github.com/yanaagi/cs-expo-2023/assets/18277662/b5112c63-2778-4467-8f12-3155df93a7ff)

Because I use GlideJS's CDN link in layout.tsx. The code editor can't find the GlideJS resources in the app because it's not there YET. But once it runs, the layout.tsx will get the GlideJS resources through the CDN link.

This is just an editor-specific warning that you can safely ignore. 😆
